extends: airbnb
plugins:
  - import
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    impliedStrict: true
    experimentalObjectRestSpread: true
    jsx: true
env:
  browser: true
globals:
  __DEV__: false
settings:
  import/extensions:
        - .js
  import/resolver:
    webpack:
      config: webpack.client.js
rules:
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/extensions: 0
  import/prefer-default-export: 0
  jsx-a11y/no-static-element-interactions: 0
  react/prop-types: 2
  no-unused-expressions: 0
  react/jsx-filename-extension: 0
  react/jsx-no-bind: 0
  no-plusplus: 0
  react/forbid-prop-types: 0
  space-before-function-paren: [
    2,
    'always',
  ]
  no-restricted-syntax: 0
  dot-notation: 0
  import/no-webpack-loader-syntax: 0
  import/first: 0
  global-require: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  react/no-array-index-key: 2
  no-confusing-arrow: 1
  jsx-quotes: [
    2,
    'prefer-single'
  ]
  arrow-parens: [
    2,
    'as-needed'
  ]
  strict: 1